### ISSUE TITLE
Getting 404 error

### ISSUE THREAD

**Issue by TomerGamerTV** [ryan-0324/vendetta-plugins#2]
I'm trying to import your plugin but I'm getting 404 error

**Comment by ryan-0324** [comment]
Inputting the URL https://ryan-0324.github.io/vendetta-plugins/FakeProfileThemesAndEffects/ works for me. However, for security reasons, I do not recommend using the non-proxy URL of any plugin; use the proxy URL (e.g., https://vd-plugins.github.io/proxy/ryan-0324.github.io/vendetta-plugins/FakeProfileThemesAndEffects/) instead.
